name: pubglobalupdate
version: 0.3.3
description: Helper to update global activated packages
author: Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/pubglobalupdate.dart
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  args: '>=1.0.2'
  process_run: '>=0.5.5'
  pub_semver: '>=1.3.2'
  path: '>=1.4.2'
dev_dependencies:
  dev_test: '>=0.9.3'
  test: '>=0.12.26'
executables:
  pubglobalupdate:

