name: pubglobalupdate
version: 0.5.3
description: Helper to update global activated packages, all at once or by package name
homepage: https://github.com/tekartik/pubglobalupdate.dart

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: '>=2.0.0 <4.0.0'
  process_run: '>=0.12.0 <2.0.0'
  pub_semver: '>=2.0.0 <4.0.0'
  path: '>=1.8.0 <3.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  dev_test: '>=0.15.0'
  test: '>=1.16.2'
  yaml: '>=3.0.0'

executables:
  pubglobalupdate:
