name: pubglobalupdate
version: 0.4.0+2
description: Helper to update global activated packages, all at once or by package name
author: Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/pubglobalupdate.dart
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  args: '>=1.0.2 <3.0.0'
  process_run: '>=0.6.0 <2.0.0'
  pub_semver: '>=1.3.2 <3.0.0'
  path: '>=1.6.1 <3.0.0'
dev_dependencies:
  dev_test: '>=0.12.0'
  test: any
executables:
  pubglobalupdate:

