name: pubglobalupdate
version: 0.1.0
description: Helper to update all global activated package
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  cmdo:
    git: git://github.com/tekartik/cmdo.dart
dev_dependencies:
  dev_test: any
  test: any
executables:
  pubglobalupdate:
