name: pubglobalupdate
version: 0.3.1
description: Helper to update global activated packages
author: Tekartik <dev@tekartik.com>
homepage: https://github.com/tekartik/pubglobalupdate.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  process_run: any
  pub_semver: any
  path: any
dev_dependencies:
  dev_test: any
  test: any
executables:
  pubglobalupdate:
#dependency_overrides:
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
